Fix namespace in RAZOR page _LoginPartial.cshtml, so nocompilation error when doing dotnet publish from CLI. Like D:\GITREPOS\eShopOnContainers-dev\src\Services\Identity\Identity.API\Views\Shared\_LoginPartial.cshtml(2,20): error CS0234: The type  or namespace name 'Models' does not exist in the namespace 'Identity.API' (are you missing an assembly reference?)